'use client';

import { useEffect, useMemo, useState } from 'react';

const EMPTY={mawb:'',bags:'',weight:'',origin:'',arrivalDate:'',arrivalTime:'',carrierCode:'',flightNo:''};

const AIRLINES={
'001':{name:'American Airlines Cargo',iata:'AA',official:'https://www.aacargo.com/'},'006':{name:'Delta Cargo',iata:'DL',official:'https://www.deltacargo.com/'},'014':{name:'Air Canada Cargo',iata:'AC',official:'https://www.aircanada.com/cargo/'},'016':{name:'United Cargo',iata:'UA',official:'https://www.unitedcargo.com/'},'020':{name:'Lufthansa Cargo',iata:'LH',official:'https://www.lufthansa-cargo.com/'},'023':{name:'FedEx Express',iata:'FX',official:'https://www.fedex.com/en-us/tracking.html'},'057':{name:'Air France KLM Martinair Cargo',iata:'AF',official:'https://www.afklcargo.com/'},'065':{name:'Saudia Cargo',iata:'SV',official:'https://www.saudiacargo.com/'},'071':{name:'Ethiopian Cargo',iata:'ET',official:'https://cargo.ethiopianairlines.com/my-cargo/track-your-shipment'},'074':{name:'KLM Cargo',iata:'KL',official:'https://www.afklcargo.com/'},'075':{name:'Iberia Cargo',iata:'IB',official:'https://www.iberia.com/cargo/'},'081':{name:'Qantas Freight',iata:'QF',official:'https://freight.qantas.com/'},'098':{name:'Air India Cargo',iata:'AI',official:'https://cargo.airindia.com/'},'105':{name:'Finnair Cargo',iata:'AY',official:'https://cargo.finnair.com/'},'125':{name:'British Airways / IAG Cargo',iata:'BA',official:'https://www.iagcargo.com/'},'131':{name:'Japan Airlines Cargo',iata:'JL',official:'https://www.jal.co.jp/jalcargo/'},'157':{name:'Qatar Airways Cargo',iata:'QR',official:'https://www.qrcargo.com/s/track-your-shipment'},'160':{name:'Cathay Cargo',iata:'CX',official:'https://www.cathaycargo.com/'},'176':{name:'Emirates SkyCargo',iata:'EK',official:'https://scekprd.emirates.com/skychain/app?initial=y&service=page%2Fnwp%3ATrackshipmt'},'180':{name:'Korean Air Cargo',iata:'KE',official:'https://cargo.koreanair.com/'},'205':{name:'ANA Cargo',iata:'NH',official:'https://www.anacargo.jp/en/'},'217':{name:'Thai Airways Cargo',iata:'TG',official:'https://www.thaicargo.com/'},'232':{name:'Malaysia Airlines Cargo',iata:'MH',official:'https://www.maskargo.com/'},'235':{name:'Turkish Cargo',iata:'TK',official:'https://www.turkishcargo.com.tr/'},'297':{name:'China Airlines Cargo',iata:'CI',official:'https://cargo.china-airlines.com/'},'312':{name:'IndiGo CarGo',iata:'6E',official:'https://6ecargo.goindigo.in/FrmAWBTracking.aspx'},'406':{name:'UPS Airlines',iata:'5X',official:'https://www.ups.com/track'},'607':{name:'Etihad Cargo',iata:'EY',official:'https://www.etihadcargo.com/'},'618':{name:'Singapore Airlines Cargo',iata:'SQ',official:'https://www.singaporeair.com/'},'724':{name:'SWISS WorldCargo',iata:'LX',official:'https://www.swissworldcargo.com/'},'988':{name:'Asiana Cargo',iata:'OZ',official:'https://www.asiana-cargo.com/'},'999':{name:'Air China Cargo',iata:'CA',official:'https://www.airchinacargo.com/'}
};

function normalizeMawb(v=''){const d=String(v).replace(/\D/g,'');return d.length>=11?`${d.slice(0,3)}-${d.slice(3,11)}`:String(v).trim();}
function airlineFromMawb(mawb=''){const p=String(mawb).replace(/\D/g,'').slice(0,3);return AIRLINES[p]||{name:p?`Airline prefix ${p}`:'Unknown airline',iata:'',official:''};}
function pad(n){return String(n).padStart(2,'0');}
function localParts(value){if(!value)return{};const d=new Date(value);if(Number.isNaN(d.getTime()))return{};return{date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`};}
function arrivalDateObj(s){if(!s.arrivalDate||!s.arrivalTime)return null;const d=new Date(`${s.arrivalDate}T${s.arrivalTime}:00`);return Number.isNaN(d.getTime())?null:d;}
function mailDue(s){const d=arrivalDateObj(s);return d?new Date(d.getTime()-6*3600000).toLocaleString():'';}
function mailAlert(s){const a=arrivalDateObj(s);if(!a)return'WAITING FOR LIVE ETA';const diff=a.getTime()-Date.now();const st=String(s.status||'').toLowerCase();if(st.includes('arriv')||st.includes('rcf')||st.includes('delivered')||diff<=0)return'ARRIVED';if(diff<=3600000)return'LANDING SOON — MAIL NOW';if(diff<=21600000)return'MAIL NOW';return`MAIL AT ${new Date(a.getTime()-21600000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;}
function statusClass(status=''){const t=status.toLowerCase();if(t.includes('arriv')||t.includes('delivered')||t.includes('rcf')||t.includes('notified'))return'green';if(t.includes('late')||t.includes('delay')||t.includes('exception'))return'red';if(t.includes('early'))return'pink';return'white';}
function extractMawb(text=''){const m=text.replace(/\s+/g,' ').match(/(?:MAWB(?:\s*No\.?)?\s*[:#-]*\s*)?(\d{3})[-\s]?(\d{8})\b/i);return m?`${m[1]}-${m[2]}`:'';}
function trustedAirlineSource(d={}){return Boolean(d.airlinePrimary)||/trackjet handoff|carrier official result|official website|official tracker/i.test(String(d.source||d.shipment?.source||''));}
function sanitizedFallback(d={}){return /diagnostic|sanitized fallback|not trusted|waiting for .* (live|official) data/i.test(`${d.source||''} ${d.shipment?.source||''} ${d.shipment?.status||''}`);}

export default function Home(){
 const[shipments,setShipments]=useState([]),[form,setForm]=useState(EMPTY),[manualOpen,setManualOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[apiConfigured,setApiConfigured]=useState(null),[ocrProgress,setOcrProgress]=useState(''),[bagEditId,setBagEditId]=useState(''),[bagEditValue,setBagEditValue]=useState('');
 useEffect(()=>{try{setShipments(JSON.parse(localStorage.getItem('mayaviShipments')||'[]'));}catch{}fetch('/api/track').then(r=>r.json()).then(d=>setApiConfigured(Boolean(d.configured))).catch(()=>setApiConfigured(false));},[]);
 useEffect(()=>{localStorage.setItem('mayaviShipments',JSON.stringify(shipments));},[shipments]);
 const activeCount=useMemo(()=>shipments.filter(s=>!String(s.status||'').toLowerCase().match(/arriv|deliver|notified/)).length,[shipments]);
 function upsertMawbOnly(mawb,sourceLabel=''){const key=normalizeMawb(mawb),airline=airlineFromMawb(key);setShipments(v=>{const i=v.findIndex(x=>normalizeMawb(x.mawb)===key);const base={...EMPTY,mawb:key,airlineName:airline.name,airlineIata:airline.iata,officialTracker:airline.official,status:'MAWB IDENTIFIED — FINDING LIVE SHIPMENT DATA',pipelineStage:'1 MAWB → 2 TRACKJET → 3 AIRLINE → 4 LIVE DATA',updatedAt:new Date().toISOString(),remarks:sourceLabel?`MAWB read from ${sourceLabel}`:''};if(i<0)return[{...base,id:crypto.randomUUID()},...v];const c=[...v];c[i]={...c[i],...base,id:c[i].id,bags:c[i].bags||'',weight:c[i].weight||''};return c;});}
 function saveManual(e){e.preventDefault();if(!form.mawb)return setNotice('Enter a MAWB number.');upsertMawbOnly(form.mawb);setForm(EMPTY);setManualOpen(false);setNotice('MAWB saved. Mayavi will route it through TrackJet to the airline.');}
 function startBagEdit(s){setBagEditId(s.id);setBagEditValue(s.bags||'');}
 function saveBags(id){const value=String(bagEditValue).replace(/\D/g,'');setShipments(v=>v.map(x=>x.id===id?{...x,bags:value,updatedAt:new Date().toISOString()}:x));setBagEditId('');setBagEditValue('');}
 async function trackOne(id,forceRefresh=false){const s=shipments.find(x=>x.id===id);if(!s)return;const airline=airlineFromMawb(s.mawb);setBusy(true);setNotice(`Checking ${s.mawb}: TrackJet → ${airline.name} → live shipment result…`);try{const r=await fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mawb:s.mawb,forceRefresh})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Tracking request failed');const live=d.shipment||{},trusted=trustedAirlineSource(d),sanitized=sanitizedFallback(d),converted=localParts(live.actualArrival||live.eta),p=(live.arrivalDate&&live.arrivalTime)?{date:live.arrivalDate,time:live.arrivalTime}:converted,liveBags=live.bags??live.pieces??live.pcs??'',liveWeight=live.weight??live.grossWeight??'',dbg=d.trackingDebug||d.airlineDebug||{},debugStage=dbg.stage||'',diagError=d.trackingError||d.airlineError||'',handoff=dbg.handoff?.text||'',carrierUrl=dbg.carrierUrl||'';const diagText=[debugStage,handoff?`handoff=${handoff}`:'',diagError,carrierUrl?`carrier=${carrierUrl}`:''].filter(Boolean).join(' · ');setShipments(v=>v.map(x=>x.id===id?{...x,bags:liveBags!==''?liveBags:x.bags,weight:liveWeight!==''?liveWeight:x.weight,carrierCode:live.carrierCode||x.carrierCode,flightNo:sanitized?'':(live.flightNo||x.flightNo),origin:sanitized?'':(live.origin||x.origin),arrivalDate:sanitized?'':(p.date||x.arrivalDate),arrivalTime:sanitized?'':(p.time||x.arrivalTime),status:sanitized?`TRACKJET/CARRIER STOPPED AT ${debugStage||'UNKNOWN STAGE'}`:(live.status||x.status),pipelineStage:p.date&&p.time?'LIVE ARRIVAL RECEIVED — MAYAVI ALERT ACTIVE':(debugStage==='SUCCESS'?'LIVE SHIPMENT DATA RECEIVED — ARRIVAL TIME NOT SHOWN YET':`DIAGNOSTIC: ${debugStage||'NO STAGE'}`),dataSource:trusted?(d.provider||'TRACKJET → AIRLINE'):(d.source||live.source||'FALLBACK'),updatedAt:new Date().toISOString(),remarks:p.date&&p.time?`Carrier arrival ${p.date} ${p.time}${live.flightNo?` · ${live.flightNo}`:''}`:(diagText||`No verified arrival yet · ${d.source||live.source||'source checked'}`)}:x));if(p.date&&p.time)setNotice(`${airline.name}: carrier result received — ${p.date} ${p.time}${live.flightNo?` · ${live.flightNo}`:''}. Mayavi 6-hour alert is active.`);else if(debugStage==='SUCCESS')setNotice(`${airline.name}: shipment details received through TrackJet, but the carrier page did not expose a reliable arrival time yet.`);else setNotice(`${airline.name} exact stop: ${diagText||'no readable carrier result'}.`);}catch(e){setNotice(`Live tracking error: ${e.message}`);}finally{setBusy(false);}}
 async function refreshAll(){for(const s of shipments)await trackOne(s.id,false);}
 async function runOcr(source){setOcrProgress('OCR reading image…');const{createWorker}=await import('tesseract.js');const w=await createWorker('eng',1,{logger:m=>{if(m.status)setOcrProgress(`${m.status} ${m.progress?Math.round(m.progress*100)+'%':''}`);}});const{data}=await w.recognize(source);await w.terminate();return data.text||'';}
 async function readPdf(file){setOcrProgress('Reading PDF text…');const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=`https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.mjs`;const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();text+=' '+c.items.map(x=>x.str).join(' ');}if(text.replace(/\s/g,'').length>20)return text;const p=await pdf.getPage(1),vp=p.getViewport({scale:2}),canvas=document.createElement('canvas');canvas.width=vp.width;canvas.height=vp.height;await p.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;return runOcr(canvas.toDataURL('image/png'));}
 async function uploadFile(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{const text=file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')?await readPdf(file):await runOcr(file);const mawb=extractMawb(text);if(!mawb)throw new Error('Could not confidently find an 11-digit MAWB.');upsertMawbOnly(mawb,file.name);setNotice(`MAWB found: ${mawb}. Mayavi will use TrackJet as the routing point and then read the airline result.`);}catch(e){setNotice(`Upload/OCR error: ${e.message}`);}finally{setBusy(false);setOcrProgress('');}}
 function remove(id){setShipments(v=>v.filter(x=>x.id!==id));}
 return <main><header><div><h1>MAYAVI CARGO</h1><p>MAWB → TrackJet → Airline → Live Cargo Data → 6-Hour Mail</p></div><div className="right"><div>{new Date().toLocaleDateString('en-IN')}</div><span className={apiConfigured?'live':'offline'}>{apiConfigured?'● TRACKJET ROUTER READY':'● TRACKJET ROUTER OFFLINE'}</span></div></header>
 <section className="toolbar"><button className="primary" onClick={()=>setManualOpen(true)}>+ Manual Entry</button><label className="button">Upload Pic / PDF<input type="file" accept="image/*,.pdf,application/pdf" hidden onChange={uploadFile}/></label><button onClick={refreshAll} disabled={busy||!shipments.length}>Refresh Status</button><div className="summary">{shipments.length} shipment(s) · {activeCount} active</div></section>
 {(notice||ocrProgress)&&<div className="notice">{ocrProgress||notice}</div>}
 <section className="tableWrap"><table><thead><tr><th>MAWB</th><th>Airline</th><th>Flight</th><th>Bags</th><th>Weight</th><th>Origin</th><th>Arrival Date</th><th>Arrival Time</th><th>Mail Due</th><th>Mail Alert</th><th>Status</th><th>Source / Stage</th><th></th></tr></thead><tbody>{!shipments.length?<tr><td colSpan="13" className="empty">No shipments yet.</td></tr>:shipments.map(s=>{const airline=airlineFromMawb(s.mawb);return <tr key={s.id} className={statusClass(s.status)}><td><b>{s.mawb}</b></td><td><b>{s.airlineName||airline.name}</b>{(s.officialTracker||airline.official)&&<small><a href={s.officialTracker||airline.official} target="_blank" rel="noreferrer">Official tracker ↗</a></small>}</td><td>{s.flightNo||'—'}</td><td>{bagEditId===s.id?<span><input style={{width:'65px'}} inputMode="numeric" value={bagEditValue} onChange={e=>setBagEditValue(e.target.value)}/><button onClick={()=>saveBags(s.id)}>Save</button></span>:<span>{s.bags||'—'} <button onClick={()=>startBagEdit(s)}>Edit</button></span>}</td><td>{s.weight?`${s.weight} kg`:'—'}</td><td>{s.origin||'—'}</td><td>{s.arrivalDate||'—'}</td><td>{s.arrivalTime||'—'}</td><td>{mailDue(s)||'—'}</td><td><b>{mailAlert(s)}</b></td><td><b>{s.status||'—'}</b><small>{s.updatedAt?`Updated ${new Date(s.updatedAt).toLocaleTimeString()}`:''}</small></td><td><b>{s.dataSource||'—'}</b><small>{s.pipelineStage||''}</small><small>{s.remarks||''}</small></td><td className="actions"><button onClick={()=>trackOne(s.id,false)} disabled={busy}>Track Live</button><button className="x" onClick={()=>remove(s.id)}>×</button></td></tr>})}</tbody></table></section>
 <section className="help"><b>Current routing:</b> Mayavi enters the MAWB on TrackJet first, follows TrackJet's verified carrier handoff, then reads the airline shipment result. If an airline presents a CAPTCHA/access challenge, Mayavi reports that exact stage and does not bypass it.</section>
 {manualOpen&&<div className="modal"><form onSubmit={saveManual}><h2>Add Shipment</h2><div className="grid"><label>MAWB*<input value={form.mawb} onChange={e=>setForm({...form,mawb:e.target.value})} placeholder="157-51777880" required/></label></div><div className="modalBtns"><button type="button" onClick={()=>setManualOpen(false)}>Cancel</button><button className="primary" type="submit">Save MAWB</button></div></form></div>}</main>;
}
