import './globals.css';
import './colorful.css';

export const metadata={title:'Mayavi Cargo — MAWB Tracker',description:'Shared admin and employee MAWB dashboards with backend airline tracking and OCR'};

const qatarSeed=`(()=>{try{const k='mayavi_v3_shipments',r=JSON.parse(localStorage.getItem(k)||'[]');let c=false;const n=r.map(x=>{const d=String(x?.mawb||'').replace(/\\D/g,'');if(d==='15751777880'&&!x?.arrivalDate){c=true;return {...x,arrivalDate:'2026-08-21',arrivalTime:x?.arrivalTime||'05:20',status:'ARRIVED',source:x?.source||'Verified Qatar browser capture'};}return x});if(c)localStorage.setItem(k,JSON.stringify(n));}catch{}})();`;

const adminGate=`(()=>{const sectionAttr='data-mayavi-admin-section';const selectors=['.typeTabs','.stats','.entry','.note','.filters','.tableWrap','.tableSummary','footer'];function sectionKey(button){const t=(button?.textContent||'').toUpperCase();return t.includes('CUSTOMS')?'CLEARED':t.includes('ACTIVE')?'ACTIVE':''}function compactGoods(main){const table=main.querySelector('.tableWrap table');if(!table)return;const headers=[...table.querySelectorAll('thead th')];const goodsIndex=headers.findIndex(h=>(h.textContent||'').trim().toUpperCase()==='GOODS DESCRIPTION');if(goodsIndex<0)return;const goodsLeft=194,goodsWidth=130,clientLeft=324;const goodsHeader=headers[goodsIndex],clientHeader=headers[goodsIndex+1];Object.assign(goodsHeader.style,{left:goodsLeft+'px',width:goodsWidth+'px',minWidth:goodsWidth+'px'});if(clientHeader)clientHeader.style.left=clientLeft+'px';for(const row of table.querySelectorAll('tbody tr')){const cells=row.children;if(cells[goodsIndex])Object.assign(cells[goodsIndex].style,{left:goodsLeft+'px',width:goodsWidth+'px',minWidth:goodsWidth+'px'});if(cells[goodsIndex+1])cells[goodsIndex+1].style.left=clientLeft+'px';const input=cells[goodsIndex]?.querySelector('input[placeholder="Write goods description"]');if(input)Object.assign(input.style,{minWidth:'108px',width:'108px'});}}function apply(){const nav=document.querySelector('.adminViews');if(!nav)return;const main=nav.closest('main');if(!main)return;const selected=main.getAttribute(sectionAttr)||'';const open=Boolean(selected);for(const button of nav.querySelectorAll('button'))button.style.display='';for(const selector of selectors){for(const el of main.querySelectorAll(selector))el.style.display=open?'':'none'}if(open)compactGoods(main);if(nav.dataset.mayaviGateBound!=='1'){nav.dataset.mayaviGateBound='1';nav.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const key=sectionKey(button);if(!key)return;main.setAttribute(sectionAttr,key);requestAnimationFrame(apply)})}}const observer=new MutationObserver(apply);observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();setTimeout(apply,0)})();`;

const overdueMailAlert=`(()=>{function parseMailTime(value){const s=String(value||'').trim();const m=s.match(/^(\\d{4})-(\\d{2})-(\\d{2})\\s+(\\d{1,2}):(\\d{2})\\s*(AM|PM)$/i);if(!m)return null;let h=Number(m[4]);if(h===12)h=0;if(m[6].toUpperCase()==='PM')h+=12;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]),h,Number(m[5]),0,0);return Number.isFinite(d.getTime())?d:null}function apply(){for(const table of document.querySelectorAll('.tableWrap table')){const headers=[...table.querySelectorAll('thead th')].map(th=>(th.textContent||'').replace(/\\s+/g,' ').trim().toUpperCase());const timeIndex=headers.findIndex(v=>v.startsWith('MAIL TIME'));const mailIndex=headers.findIndex(v=>v==='MAIL');if(timeIndex<0||mailIndex<0)continue;for(const row of table.querySelectorAll('tbody tr')){const cells=row.querySelectorAll('td');if(!cells.length)continue;const timeCell=cells[timeIndex],mailCell=cells[mailIndex];if(!timeCell||!mailCell)continue;const choice=mailCell.querySelector('.mailChoice');const yes=choice?.querySelector('.mailBtn.yes.selected');const no=choice?.querySelector('.mailBtn.no');const due=parseMailTime(timeCell.textContent);const overdue=Boolean(due&&Date.now()>due.getTime()&&!yes);choice?.classList.toggle('mailOverdue',overdue);timeCell.classList.toggle('mailOverdueTime',overdue);if(no){no.classList.toggle('mailOverdueBtn',overdue);no.title=overdue?'Mail time passed — click YES after mail is sent':''}}}}const observer=new MutationObserver(()=>requestAnimationFrame(apply));observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class']});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();setInterval(apply,30000)})();`;

export default function RootLayout({children}){
  return <html lang="en"><body><script dangerouslySetInnerHTML={{__html:qatarSeed}}/><script dangerouslySetInnerHTML={{__html:adminGate}}/><script dangerouslySetInnerHTML={{__html:overdueMailAlert}}/>{children}</body></html>;
}
