import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=60;
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
async function launch(){chromium.setGraphicsMode=false;return puppeteer.launch({args:[...chromium.args,'--no-sandbox','--disable-setuid-sandbox'],defaultViewport:{width:1440,height:1200},executablePath:await chromium.executablePath(),headless:'shell'});}
async function typeCandidate(page,selector,value){const el=await page.$(selector);if(!el)return {ok:false,value:''};await el.click({clickCount:3});await page.keyboard.press('Backspace').catch(()=>{});await el.type(value,{delay:45});await page.evaluate(({selector})=>{const i=document.querySelector(selector);if(!i)return;i.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));i.dispatchEvent(new Event('change',{bubbles:true}));i.dispatchEvent(new FocusEvent('blur',{bubbles:true}));},{selector});await new Promise(r=>setTimeout(r,250));return page.evaluate(({selector})=>{const i=document.querySelector(selector);return {ok:Boolean(i),value:i?.value||'',maxLength:i?.maxLength||null,outer:i?.outerHTML?.slice(0,1200)||''};},{selector});}
export async function GET(request){const q=new URL(request.url).searchParams.get('mawb')||'17661041886';const digits=String(q).replace(/\D/g,'');if(!/^176\d{8}$/.test(digits))return Response.json({ok:false,error:'Use valid Emirates 176 MAWB'},{status:400});const serial=digits.slice(3);let browser;try{browser=await launch();const page=await browser.newPage();await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/149 Safari/537.36');const net=[];const tasks=[];page.on('response',res=>{const t=(async()=>{try{const req=res.request(),type=req.resourceType(),url=res.url(),ct=(res.headers()['content-type']||'').toLowerCase();if(!['xhr','fetch','document'].includes(type))return;if(!/emirates|eskycargo|api/i.test(url))return;let snippet='';if(/json|text|html/.test(ct)){const txt=clean(await res.text());if(txt.includes(digits)||txt.includes(serial)||/shipment|tracking|airway|document|flight|arrival|pieces|weight/i.test(txt))snippet=txt.slice(0,10000);}if(snippet||url.includes('api/'))net.push({status:res.status(),method:req.method(),type,url,snippet});}catch{}})();tasks.push(t)});
await page.goto('https://eskycargo.emirates.com/app/offerandorder/',{waitUntil:'domcontentloaded',timeout:20000});await new Promise(r=>setTimeout(r,3000));await page.evaluate(()=>{const t=[...document.querySelectorAll('button,a,[role="button"]')].find(e=>/^(accept|allow all)$/i.test(String(e.innerText||e.getAttribute('aria-label')||'').trim()));t?.click()}).catch(()=>{});await new Promise(r=>setTimeout(r,5500));
const selector='input[placeholder*="Doc. No."]';const input=await page.$(selector);if(!input)return Response.json({ok:false,error:'DOC NUMBER FIELD NOT FOUND'},{status:503});const meta=await page.evaluate(({selector})=>{const i=document.querySelector(selector);return {maxLength:i?.maxLength||null,placeholder:i?.placeholder||'',outer:i?.outerHTML?.slice(0,1200)||''};},{selector});
const candidates=meta.maxLength>0&&meta.maxLength<=8?[serial]:[serial,digits,`176-${serial}`];let bound=null,used='';for(const candidate of candidates){bound=await typeCandidate(page,selector,candidate);if(bound?.value===candidate){used=candidate;break;}}
if(!used)return Response.json({ok:false,error:'EMIRATES INPUT NOT BOUND',mawb:digits,serial,meta,bound},{status:503});
const clicked=await page.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(e=>/^Search$/i.test(String(e.innerText||'').trim()));if(b){b.focus();b.click();return true}return false});await new Promise(r=>setTimeout(r,8000));await Promise.allSettled(tasks);
const data=await page.evaluate(({digits,serial,selector})=>{const c=s=>String(s||'').replace(/\s+/g,' ').trim();const body=c(document.body?.innerText||'');const rows=[...document.querySelectorAll('tr')].map(x=>c(x.innerText)).filter(Boolean);const nodes=[...document.querySelectorAll('a,button,[role="button"],div,span,td')].map((e,i)=>({i,text:c(e.innerText||e.getAttribute('aria-label')||e.getAttribute('title')||''),href:e.href||'',tag:e.tagName,outer:e.outerHTML.slice(0,800)})).filter(x=>x.text&&(x.text.includes(digits)||x.text.includes(serial)||/tracking details|shipment|176|flight|arriv|pieces|weight|status|document no|details/i.test(x.text))).slice(0,250);const inputValue=document.querySelector(selector)?.value||'';return{title:document.title,url:location.href,inputValue,body:body.slice(0,30000),rows:rows.slice(0,120),nodes};},{digits,serial,selector});const shot=await page.screenshot({type:'jpeg',quality:72,fullPage:true,encoding:'base64'}).catch(()=>null);return Response.json({ok:true,mawb:digits,serial,usedInput:used,clicked,meta,screenshotCaptured:Boolean(shot),network:net.slice(-100),...data});}catch(e){return Response.json({ok:false,error:e?.message||String(e)},{status:503})}finally{try{if(browser)await browser.close()}catch{}}}
