import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=60;
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
async function launch(){chromium.setGraphicsMode=false;return puppeteer.launch({args:[...chromium.args,'--no-sandbox','--disable-setuid-sandbox'],defaultViewport:{width:1440,height:1200},executablePath:await chromium.executablePath(),headless:'shell'});}
async function setNativeValue(page,selector,value){return page.evaluate(({selector,value})=>{const el=document.querySelector(selector);if(!el)return {ok:false,value:null};const proto=Object.getPrototypeOf(el);const desc=Object.getOwnPropertyDescriptor(proto,'value')||Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');desc?.set?.call(el,value);el.focus();el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:value}));el.dispatchEvent(new Event('change',{bubbles:true}));el.dispatchEvent(new FocusEvent('blur',{bubbles:true}));return {ok:true,value:el.value};},{selector,value});}
export async function GET(request){const q=new URL(request.url).searchParams.get('mawb')||'17661041886';const digits=String(q).replace(/\D/g,'');if(!/^176\d{8}$/.test(digits))return Response.json({ok:false,error:'Use valid Emirates 176 MAWB'},{status:400});let browser;try{browser=await launch();const page=await browser.newPage();await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/149 Safari/537.36');const net=[];const tasks=[];page.on('response',res=>{const t=(async()=>{try{const req=res.request(),type=req.resourceType(),url=res.url(),ct=(res.headers()['content-type']||'').toLowerCase();if(!['xhr','fetch','document'].includes(type))return;if(!/emirates|eskycargo|api/i.test(url))return;let snippet='';if(/json|text|html/.test(ct)){const txt=clean(await res.text());if(txt.includes(digits)||/shipment|tracking|airway|document|flight|arrival|pieces|weight/i.test(txt))snippet=txt.slice(0,8000);}if(snippet||url.includes('api/'))net.push({status:res.status(),method:req.method(),type,url,snippet});}catch{}})();tasks.push(t)});
await page.goto('https://eskycargo.emirates.com/app/offerandorder/',{waitUntil:'domcontentloaded',timeout:20000});await new Promise(r=>setTimeout(r,3000));await page.evaluate(()=>{const t=[...document.querySelectorAll('button,a,[role="button"]')].find(e=>/^(accept|allow all)$/i.test(String(e.innerText||e.getAttribute('aria-label')||'').trim()));t?.click()}).catch(()=>{});await new Promise(r=>setTimeout(r,5500));
const selector='input[placeholder*="Doc. No."]';const input=await page.$(selector);if(!input)return Response.json({ok:false,error:'DOC NUMBER FIELD NOT FOUND'},{status:503});await input.click({clickCount:3});await page.keyboard.press('Backspace').catch(()=>{});let bound=await setNativeValue(page,selector,digits);if(!bound?.ok||bound.value!==digits){await input.type(digits,{delay:35});bound=await page.evaluate(({selector})=>{const el=document.querySelector(selector);return {ok:Boolean(el),value:el?.value||''};},{selector});}
await new Promise(r=>setTimeout(r,350));const beforeSearch=await page.evaluate(({selector})=>{const el=document.querySelector(selector);const validation=[...document.querySelectorAll('*')].map(e=>String(e.innerText||'').trim()).find(t=>/enter at least one search parameter/i.test(t))||'';return {value:el?.value||'',validation};},{selector});if(beforeSearch.value!==digits)return Response.json({ok:false,error:'EMIRATES INPUT NOT BOUND',mawb:digits,beforeSearch},{status:503});
const clicked=await page.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(e=>/^Search$/i.test(String(e.innerText||'').trim()));if(b){b.focus();b.click();return true}return false});await new Promise(r=>setTimeout(r,7500));await Promise.allSettled(tasks);
const data=await page.evaluate(({digits,selector})=>{const c=s=>String(s||'').replace(/\s+/g,' ').trim();const body=c(document.body?.innerText||'');const rows=[...document.querySelectorAll('tr')].map(x=>c(x.innerText)).filter(Boolean);const nodes=[...document.querySelectorAll('a,button,[role="button"],div,span,td')].map((e,i)=>({i,text:c(e.innerText||e.getAttribute('aria-label')||e.getAttribute('title')||''),href:e.href||'',tag:e.tagName,outer:e.outerHTML.slice(0,800)})).filter(x=>x.text&&(x.text.includes(digits)||/tracking details|shipment|176|flight|arriv|pieces|weight|status|document no|details/i.test(x.text))).slice(0,250);const inputValue=document.querySelector(selector)?.value||'';return{title:document.title,url:location.href,inputValue,body:body.slice(0,30000),rows:rows.slice(0,120),nodes};},{digits,selector});const shot=await page.screenshot({type:'jpeg',quality:72,fullPage:true,encoding:'base64'}).catch(()=>null);return Response.json({ok:true,mawb:digits,clicked,beforeSearch,screenshotCaptured:Boolean(shot),network:net.slice(-100),...data});}catch(e){return Response.json({ok:false,error:e?.message||String(e)},{status:503})}finally{try{if(browser)await browser.close()}catch{}}}
