import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
export const runtime='nodejs'; export const dynamic='force-dynamic'; export const maxDuration=90;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
async function launch(){chromium.setGraphicsMode=false;return puppeteer.launch({args:[...chromium.args,'--no-sandbox','--disable-setuid-sandbox','--disable-blink-features=AutomationControlled'],executablePath:await chromium.executablePath(),headless:'shell',defaultViewport:{width:1440,height:1200}})}
export async function GET(request){
 const u=new URL(request.url),d=String(u.searchParams.get('mawb')||'23218849773').replace(/\D/g,''),mawb=d.length>=11?d.slice(0,3)+'-'+d.slice(3,11):d;let browser;
 try{browser=await launch();const page=await browser.newPage();await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/149 Safari/537.36');await page.setExtraHTTPHeaders({'Accept-Language':'en-US,en;q=0.9'});
 const captures=[];page.on('response',async response=>{try{const url=response.url(),ct=String(response.headers()['content-type']||'').toLowerCase();if(!/json|text|javascript/.test(ct)&&!/track|air|cargo|awb|shipment|api/i.test(url))return;const body=await response.text();if(!body)return;if(body.includes(d)||/awb|shipment|cargo|flight|origin|destination|status|tracking/i.test(body)){captures.push({url,status:response.status(),ct,body:clean(body).slice(0,10000)});if(captures.length>50)captures.shift()}}catch{}});
 await page.goto('https://www.gocomet.com/online-cargo-tracking/carriers/malaysian-airlines',{waitUntil:'domcontentloaded',timeout:30000});await sleep(4000);
 const before=await page.evaluate(()=>({url:location.href,text:(document.body?.innerText||'').slice(0,12000),inputs:[...document.querySelectorAll('input')].map((e,i)=>({i,type:e.type,name:e.name,id:e.id,placeholder:e.placeholder,aria:e.getAttribute('aria-label'),value:e.value,disabled:e.disabled})).slice(0,60),buttons:[...document.querySelectorAll('button,[role="button"],input[type="submit"],a')].map((e,i)=>({i,tag:e.tagName,text:(e.innerText||e.value||e.textContent||'').replace(/\s+/g,' ').trim(),href:e.href||'',disabled:e.disabled||false})).filter(x=>x.text).slice(0,160)}));
 const fill=await page.evaluate(({mawb})=>{const inputs=[...document.querySelectorAll('input')];const input=inputs.find(e=>/master|awb|booking|tracking/i.test([e.placeholder,e.name,e.id,e.getAttribute('aria-label')].join(' ')))||inputs.find(e=>e.type==='text');if(!input)return{ok:false,reason:'no input'};const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(input,mawb);if(!setter)input.value=mawb;input.focus();input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keyup',{bubbles:true,key:'1'}));return{ok:true,value:input.value}}, {mawb});
 await sleep(1000);
 const controls=await page.evaluate(()=>[...document.querySelectorAll('button,[role="button"],input[type="submit"],a')].map((e,i)=>({i,tag:e.tagName,text:(e.innerText||e.value||e.textContent||'').replace(/\s+/g,' ').trim(),disabled:e.disabled||false,outer:e.outerHTML.slice(0,800)})).filter(x=>/track|search|submit/i.test(x.text)).slice(0,30));
 const clicked=await page.evaluate(()=>{const els=[...document.querySelectorAll('button,[role="button"],input[type="submit"],a')];const txt=e=>(e.innerText||e.value||e.textContent||'').replace(/\s+/g,' ').trim();const b=els.find(e=>/^track$/i.test(txt(e))&&!e.disabled)||els.find(e=>/track/i.test(txt(e))&&!e.disabled);if(!b)return'';b.click();return txt(b)});
 await Promise.race([page.waitForNetworkIdle({idleTime:1000,timeout:20000}).catch(()=>{}),sleep(12000)]);await sleep(2000);
 const after=await page.evaluate(()=>({url:location.href,text:(document.body?.innerText||'').slice(0,20000)}));
 return Response.json({ok:true,mawb,fill,controls,clicked,before,after,captures});
 }catch(e){return Response.json({ok:false,error:String(e?.message||e)},{status:500})}finally{try{if(browser)await browser.close()}catch{}}
}